language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "899796"
    token:899796
      secure: "b3c365092f5ed28ad592c5fa196819dd7e589fe2"
jdk:
  - oraclejdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
      